get http://localhost:3003/api/posts?postId=61b41ec74daacc240e218001

################################
POST http://localhost:3004/api/topics
Content-Type: application/json

{
    "title":"Topic 1",
    "postId": "61b41ec74daacc240e218001",
    "textHighlight":"post 1",
    "user": "61b41defd2dcd99d22f0b6cc"
}
########
POST http://localhost:3005/api/comment
Content-Type: application/json

{
    "user":"61b41defd2dcd99d22f0b6cc",
    "topic":"61b606a54486a729e24b15e9",
    "content":"Hello Post 1"
}
################################
PUT http://localhost:3005/api/comment/61b57ce40c848cb0a5398986
Content-Type: application/json

{
    "content": "sorry, it's so very good"
}
################################
DELETE http://localhost:3005/api/comment/61b5ee679ee7ffb5cff41bca
########
PUT http://localhost:3004/api/topic/61b49052257f3e202500c656
Content-Type: application/json

{
    "title":"Edit second"
}
########
delete http://localhost:3004/api/topic/61b606a54486a729e24b15e9