get http://localhost:3003/api/posts?postId=61b41ec74daacc240e218001

################################
POST http://localhost:3004/api/topics
Content-Type: application/json

{
    "title":"Topic of post 1",
    "postId": "61b802f88c5250d7519ea93c",
    "textHighlight":"post 1",
    "user": "61b41defd2dcd99d22f0b6cc"
}
########
POST http://localhost:3005/api/comment
Content-Type: application/json

{
    "user":"61b41defd2dcd99d22f0b6cc",
    "topic":"61b80305b691c9b35d45f142",
    "postId":"61b802f88c5250d7519ea93c",
    "content":"Hello topic 1"
}
################################
PUT http://localhost:3005/api/comment/61b57ce40c848cb0a5398986
Content-Type: application/json

{
    "content": "sorry, it's so very good"
}
################################
DELETE http://localhost:3005/api/comment/61b5ee679ee7ffb5cff41bca
########
PUT http://localhost:3004/api/topic/61b49052257f3e202500c656
Content-Type: application/json

{
    "title":"Edit second"
}
########
delete http://localhost:3004/api/topic/61b6b916f5995ad21adc7bd6


################################################################
delete http://localhost:3005/api/comment/topic/61b6aff5cc82c825ae151a6a
################################################################
POST http://localhost:3002/api/post/
Content-Type: application/json

{
    "title":"Post 1",
    "content": "content post 1",
    "user": "61b5d1d590551dc386ea57ae"
}



################################
PUT http://localhost:3002/api/post/61b7f888a881ad327b8f0ee2
Content-Type: application/json

{
    "title": "Post 3 Updated",
    "content":"Content Post 3 Updated"
}
########
DELETE http://localhost:3002/api/post/61b802f88c5250d7519ea93c
########
POST http://localhost:3001/api/user
Content-Type: application/json

{
    "username": "sanhtuan",
    "email": "sanhtuan@gmail.com",
    "password": "1234",
    "confirmPassword": "1234"
}


################################
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email": "sanhtuan@gmail.com",
    "password": "1234"
}
########
GET  http://localhost:3000/api/user/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE4YWEwNTk1NjA3MjgxN2Y4YTMyMWEiLCJpYXQiOjE2Mzg3NzAyNTF9.oOT-0RLrumfRiIDEI5Udh8U4CtNi1Hs35elhwYgs0nQ

################################
POST http://localhost:3002/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWI1ZDFkNTkwNTUxZGMzODZlYTU3YWUiLCJpYXQiOjE2Mzk0NzgwNTF9.ffOhFkuHz8ZVuwTDoi1FWt5AOCAN8Oxeq3vW8i5FgSY

{
    "title":"Post 4",
    "content": "content post 4",
    "user": "61b5d1d590551dc386ea57ae"
}