POST http://localhost:3001/api/user
Content-Type: application/json

{
    "username": "sanhtuan",
    "email": "sanhtuan@gmail.com",
    "password": "1234",
    "confirmPassword": "1234"
}

################################            
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "tranbinhminh16030721@gmail.com",
    "password": "123456"
}
########
GET  http://localhost:3000/api/user/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE4YWEwNTk1NjA3MjgxN2Y4YTMyMWEiLCJpYXQiOjE2Mzg3NzAyNTF9.oOT-0RLrumfRiIDEI5Udh8U4CtNi1Hs35elhwYgs0nQ

#########
POST http://localhost:3000/api/user/forgot-password
Content-Type: application/json

{
    "email":"minh@gmail.com"
}
########
PUT http://localhost:3000/api/user/reset-password
Content-Type: application/json

{
    "otp":"irbgjj",
    "email": "minh@gmail.com",
    "newPassword": "minh123455",
    "confirmPassword": "minh123455"
}